// <auto-generated />
using System;
using GlowCare.Entities;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace GlowCare.Entities.Migrations
{
    [DbContext(typeof(GlowCareDbContext))]
    [Migration("20251203083811_InitialMigration")]
    partial class InitialMigration
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("GlowCare.Entities.Models.Category", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.HasKey("Id");

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Skin Care"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Laser Treatments"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Massage"
                        },
                        new
                        {
                            Id = 4,
                            Name = "Aesthetic Medicine"
                        },
                        new
                        {
                            Id = 5,
                            Name = "Facial Treatments"
                        });
                });

            modelBuilder.Entity("GlowCare.Entities.Models.Certificate", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CertificateDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("EmployeeId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Url")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("EmployeeId");

                    b.ToTable("Certificates");
                });

            modelBuilder.Entity("GlowCare.Entities.Models.Client", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("MembershipId")
                        .HasColumnType("int");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("MembershipId");

                    b.HasIndex("UserId");

                    b.ToTable("Clients");

                    b.HasData(
                        new
                        {
                            Id = "1f4c1474-cf86-4199-9f6c-1f417b7ac9e4",
                            MembershipId = 1,
                            UserId = "e5c2g9b3-4a67-4f89-8d23-556677889900"
                        });
                });

            modelBuilder.Entity("GlowCare.Entities.Models.DayOfWeek", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.HasKey("Id");

                    b.ToTable("DaysOfWeek");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Monday"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Tuesday"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Wednesday"
                        },
                        new
                        {
                            Id = 4,
                            Name = "Thursday"
                        },
                        new
                        {
                            Id = 5,
                            Name = "Friday"
                        },
                        new
                        {
                            Id = 6,
                            Name = "Saturday"
                        },
                        new
                        {
                            Id = 7,
                            Name = "Sunday"
                        });
                });

            modelBuilder.Entity("GlowCare.Entities.Models.Employee", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Biography")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("ExperienceYears")
                        .HasColumnType("int");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("Occupation")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("Employees");

                    b.HasData(
                        new
                        {
                            Id = "66e6b9a6-4c5a-4344-bdae-6edbacc4b608",
                            Biography = "I am a licensed dermatologist with 5 years of experience helping patients achieve healthier skin. My expertise includes treating conditions such as acne, eczema, and pigmentation disorders, as well as performing advanced laser and cosmetic procedures. I am passionate about educating my patients and creating personalized treatment plans that combine proven medical methods with modern skin care innovations.",
                            ExperienceYears = 5,
                            IsDeleted = false,
                            Occupation = "Dermatologist",
                            UserId = "a7d3c5e2-9b41-4f12-8f34-123456789abc"
                        },
                        new
                        {
                            Id = "b75e8e37-95e4-44ef-a32c-10aebaff55b3",
                            Biography = "I am a certified esthetician with 10 years of experience providing skin care treatments, facials, and anti-aging therapies. My goal is to help clients achieve glowing, healthy skin using both modern techniques and natural methods.",
                            ExperienceYears = 10,
                            IsDeleted = false,
                            Occupation = "Esthetician",
                            UserId = "ac31b0bb-d05a-438d-be06-9bfe3323cf08"
                        },
                        new
                        {
                            Id = "1dccdb69-fbd1-43c4-8c17-95796b5aa95e",
                            Biography = "I am a licensed laser removal specialist with 7 years of experience in hair removal, tattoo removal, and skin resurfacing treatments. My focus is on providing safe, effective, and customized solutions for each client to achieve smooth and healthy skin.",
                            ExperienceYears = 6,
                            IsDeleted = false,
                            Occupation = "Laser Technician",
                            UserId = "29965aaa-46cf-4829-93b8-e38401be7547"
                        },
                        new
                        {
                            Id = "a0617bdf-80af-4316-a9c9-c2fd77170f7f",
                            Biography = "I am a certified massage therapist with 6 years of experience in Swedish, deep tissue, and therapeutic massage. My goal is to help clients relax, relieve stress, and improve overall well-being through personalized treatments.",
                            ExperienceYears = 6,
                            IsDeleted = false,
                            Occupation = "Massage Therapist",
                            UserId = "c9f4e7b1-2d33-4a11-8f56-abcdef123456"
                        });
                });

            modelBuilder.Entity("GlowCare.Entities.Models.EmployeeSchedule", b =>
                {
                    b.Property<string>("EmployeeId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("ScheduleId")
                        .HasColumnType("int");

                    b.HasKey("EmployeeId", "ScheduleId");

                    b.HasIndex("ScheduleId");

                    b.ToTable("EmployeesSchedules");

                    b.HasData(
                        new
                        {
                            EmployeeId = "66e6b9a6-4c5a-4344-bdae-6edbacc4b608",
                            ScheduleId = 2
                        },
                        new
                        {
                            EmployeeId = "66e6b9a6-4c5a-4344-bdae-6edbacc4b608",
                            ScheduleId = 3
                        },
                        new
                        {
                            EmployeeId = "b75e8e37-95e4-44ef-a32c-10aebaff55b3",
                            ScheduleId = 1
                        },
                        new
                        {
                            EmployeeId = "b75e8e37-95e4-44ef-a32c-10aebaff55b3",
                            ScheduleId = 3
                        },
                        new
                        {
                            EmployeeId = "1dccdb69-fbd1-43c4-8c17-95796b5aa95e",
                            ScheduleId = 4
                        },
                        new
                        {
                            EmployeeId = "a0617bdf-80af-4316-a9c9-c2fd77170f7f",
                            ScheduleId = 3
                        });
                });

            modelBuilder.Entity("GlowCare.Entities.Models.EmployeeService", b =>
                {
                    b.Property<string>("EmployeeId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("ServiceId")
                        .HasColumnType("int");

                    b.HasKey("EmployeeId", "ServiceId");

                    b.HasIndex("ServiceId");

                    b.ToTable("EmployeesServices");

                    b.HasData(
                        new
                        {
                            EmployeeId = "66e6b9a6-4c5a-4344-bdae-6edbacc4b608",
                            ServiceId = 1
                        },
                        new
                        {
                            EmployeeId = "66e6b9a6-4c5a-4344-bdae-6edbacc4b608",
                            ServiceId = 4
                        },
                        new
                        {
                            EmployeeId = "66e6b9a6-4c5a-4344-bdae-6edbacc4b608",
                            ServiceId = 5
                        },
                        new
                        {
                            EmployeeId = "66e6b9a6-4c5a-4344-bdae-6edbacc4b608",
                            ServiceId = 6
                        },
                        new
                        {
                            EmployeeId = "66e6b9a6-4c5a-4344-bdae-6edbacc4b608",
                            ServiceId = 14
                        },
                        new
                        {
                            EmployeeId = "66e6b9a6-4c5a-4344-bdae-6edbacc4b608",
                            ServiceId = 15
                        },
                        new
                        {
                            EmployeeId = "66e6b9a6-4c5a-4344-bdae-6edbacc4b608",
                            ServiceId = 16
                        },
                        new
                        {
                            EmployeeId = "66e6b9a6-4c5a-4344-bdae-6edbacc4b608",
                            ServiceId = 17
                        },
                        new
                        {
                            EmployeeId = "66e6b9a6-4c5a-4344-bdae-6edbacc4b608",
                            ServiceId = 18
                        },
                        new
                        {
                            EmployeeId = "b75e8e37-95e4-44ef-a32c-10aebaff55b3",
                            ServiceId = 6
                        },
                        new
                        {
                            EmployeeId = "b75e8e37-95e4-44ef-a32c-10aebaff55b3",
                            ServiceId = 7
                        },
                        new
                        {
                            EmployeeId = "1dccdb69-fbd1-43c4-8c17-95796b5aa95e",
                            ServiceId = 2
                        },
                        new
                        {
                            EmployeeId = "1dccdb69-fbd1-43c4-8c17-95796b5aa95e",
                            ServiceId = 8
                        },
                        new
                        {
                            EmployeeId = "1dccdb69-fbd1-43c4-8c17-95796b5aa95e",
                            ServiceId = 9
                        },
                        new
                        {
                            EmployeeId = "1dccdb69-fbd1-43c4-8c17-95796b5aa95e",
                            ServiceId = 10
                        },
                        new
                        {
                            EmployeeId = "1dccdb69-fbd1-43c4-8c17-95796b5aa95e",
                            ServiceId = 11
                        },
                        new
                        {
                            EmployeeId = "1dccdb69-fbd1-43c4-8c17-95796b5aa95e",
                            ServiceId = 12
                        },
                        new
                        {
                            EmployeeId = "b75e8e37-95e4-44ef-a32c-10aebaff55b3",
                            ServiceId = 13
                        },
                        new
                        {
                            EmployeeId = "a0617bdf-80af-4316-a9c9-c2fd77170f7f",
                            ServiceId = 3
                        },
                        new
                        {
                            EmployeeId = "a0617bdf-80af-4316-a9c9-c2fd77170f7f",
                            ServiceId = 20
                        });
                });

            modelBuilder.Entity("GlowCare.Entities.Models.GlowUser", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<int>("Age")
                        .HasColumnType("int");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("Gender")
                        .HasColumnType("int");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.ToTable("AspNetUsers", (string)null);

                    b.HasData(
                        new
                        {
                            Id = "a7d3c5e2-9b41-4f12-8f34-123456789abc",
                            AccessFailedCount = 0,
                            Age = 32,
                            ConcurrencyStamp = "4d0ec400-1384-408d-a1a7-be57f0829ce5",
                            Email = "elena.dimitrova@gmail.com",
                            EmailConfirmed = true,
                            FirstName = "Elena",
                            Gender = 1,
                            LastName = "Dimitrova",
                            LockoutEnabled = false,
                            NormalizedEmail = "ELENA.DIMITROVA@EXAMPLE.COM",
                            NormalizedUserName = "ELENA.DIMITROVA@EXAMPLE.COM",
                            PasswordHash = "AQAAAAIAAYagAAAAEBgtcOPEW8WIOFJi86gQNIBVjhFeUKIum47+l9jV1pWJQQNEygbfmVJ+/37gJaGmyQ==",
                            PhoneNumber = "0888123456",
                            PhoneNumberConfirmed = true,
                            SecurityStamp = "8eb96922-ff8f-4bf5-a9fb-9d6201397aeb",
                            TwoFactorEnabled = false,
                            UserName = "elena.dimitrova@gmail.com"
                        },
                        new
                        {
                            Id = "ac31b0bb-d05a-438d-be06-9bfe3323cf08",
                            AccessFailedCount = 0,
                            Age = 30,
                            ConcurrencyStamp = "d9e66284-ed6a-47f3-825d-5593ddc92172",
                            Email = "johndoe@gmail.com",
                            EmailConfirmed = true,
                            FirstName = "John",
                            Gender = 0,
                            LastName = "Doe",
                            LockoutEnabled = false,
                            NormalizedEmail = "JOHNDOE@EXAMPLE.COM",
                            NormalizedUserName = "JOHNDOE@EXAMPLE.COM",
                            PasswordHash = "AQAAAAIAAYagAAAAEAfUZDYLtgN+XeK8/DLGZBXLMrIt7TM0iSGraS8lqKWif7EZxE0avK9wbMYL3vohxw==",
                            PhoneNumber = "0875757574",
                            PhoneNumberConfirmed = true,
                            SecurityStamp = "87afc345-2975-4a15-b7a6-e25d7d779ed1",
                            TwoFactorEnabled = false,
                            UserName = "johndoe@gmail.com"
                        },
                        new
                        {
                            Id = "29965aaa-46cf-4829-93b8-e38401be7547",
                            AccessFailedCount = 0,
                            Age = 38,
                            ConcurrencyStamp = "61e74e67-b860-493f-935e-b310fa867d44",
                            Email = "maria.petrova@gmail.com",
                            EmailConfirmed = true,
                            FirstName = "Maria",
                            Gender = 1,
                            LastName = "Petrova",
                            LockoutEnabled = false,
                            NormalizedEmail = "MARIA.PETROVA@EXAMPLE.COM",
                            NormalizedUserName = "MARIA.PETROVA@EXAMPLE.COM",
                            PasswordHash = "AQAAAAIAAYagAAAAEFI96EZlRwRZxAHlOy9fKJvl3W9m5PcHH/CTCRKBqAqUn9c3Z7cuir8pgRBbMGuYrw==",
                            PhoneNumber = "0899123456",
                            PhoneNumberConfirmed = true,
                            SecurityStamp = "88bdeb1a-5ace-4728-a256-fe98df55e082",
                            TwoFactorEnabled = false,
                            UserName = "maria.petrova@gmail.com"
                        },
                        new
                        {
                            Id = "c9f4e7b1-2d33-4a11-8f56-abcdef123456",
                            AccessFailedCount = 0,
                            Age = 30,
                            ConcurrencyStamp = "a8a88ffa-553c-499f-a5a0-3ef307bc354c",
                            Email = "ivana.koleva@gmail.com",
                            EmailConfirmed = true,
                            FirstName = "Ivana",
                            Gender = 1,
                            LastName = "Koleva",
                            LockoutEnabled = false,
                            NormalizedEmail = "IVANA.KOLEVA@EXAMPLE.COM",
                            NormalizedUserName = "IVANA.KOLEVA@EXAMPLE.COM",
                            PasswordHash = "AQAAAAIAAYagAAAAEDphuHj1XntLBTVIk1HHNlib2Jm5hZPkd7XHfOy9Kdwf9vwiyhxG7Uz0eB0prgvvWA==",
                            PhoneNumber = "0888234567",
                            PhoneNumberConfirmed = true,
                            SecurityStamp = "277257f2-4434-4c6b-afa9-fda4e71a272c",
                            TwoFactorEnabled = false,
                            UserName = "ivana.koleva@gmail.com"
                        },
                        new
                        {
                            Id = "e5c2g9b3-4a67-4f89-8d23-556677889900",
                            AccessFailedCount = 0,
                            Age = 30,
                            ConcurrencyStamp = "07975096-e5cb-4399-8ee7-65fbbe0c7be0",
                            Email = "nikol.georgieva@gmail.com",
                            EmailConfirmed = true,
                            FirstName = "Nikol",
                            Gender = 1,
                            LastName = "Georgieva",
                            LockoutEnabled = false,
                            NormalizedEmail = "NIKOL.GEORGIEVA@EXAMPLE.COM",
                            NormalizedUserName = "NIKOL.GEORGIEVA@EXAMPLE.COM",
                            PasswordHash = "AQAAAAIAAYagAAAAEGzKABzAfOlZ1o0p5rcV+H50v9ptgzymXSYaudx/GZ8Lt/gJnfimWCA5GOHIgqEHLQ==",
                            PhoneNumber = "0855123456",
                            PhoneNumberConfirmed = true,
                            SecurityStamp = "47ac7e78-8705-4e3a-876f-17f1ccbf7c02",
                            TwoFactorEnabled = false,
                            UserName = "nikol.georgieva@gmail.com"
                        },
                        new
                        {
                            Id = "fc95b3fa-f342-4172-ac8b-5b35951ad760",
                            AccessFailedCount = 0,
                            Age = 18,
                            ConcurrencyStamp = "b6dc9ade-c214-48b1-ad21-b9b582cec08e",
                            Email = "teodora_nedkova@abv.bg",
                            EmailConfirmed = true,
                            FirstName = "Teodora",
                            Gender = 1,
                            LastName = "Nedkova",
                            LockoutEnabled = false,
                            NormalizedEmail = "TEODORA_NEDKOVA@ABV.BG",
                            NormalizedUserName = "TEODORA_NEDKOVA@ABV.BG",
                            PasswordHash = "AQAAAAIAAYagAAAAEM8FoQGtSJx4jfs+N/FmJ3gefiSkgiZwct4c0lbt1WbeTyIBlgU+dFMnTfve+GHMCg==",
                            PhoneNumber = "0878654562",
                            PhoneNumberConfirmed = true,
                            SecurityStamp = "5d3788ec-e9c0-4a26-857d-e41ef6b84c31",
                            TwoFactorEnabled = false,
                            UserName = "teodora_nedkova@abv.bg"
                        });
                });

            modelBuilder.Entity("GlowCare.Entities.Models.Membership", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("DiscountPercentage")
                        .HasColumnType("int");

                    b.Property<int>("Points")
                        .HasColumnType("int");

                    b.Property<int>("Title")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Memberships");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            DiscountPercentage = 20,
                            Points = 0,
                            Title = 0
                        },
                        new
                        {
                            Id = 2,
                            DiscountPercentage = 10,
                            Points = 500,
                            Title = 1
                        },
                        new
                        {
                            Id = 3,
                            DiscountPercentage = 15,
                            Points = 1000,
                            Title = 2
                        },
                        new
                        {
                            Id = 4,
                            DiscountPercentage = 20,
                            Points = 2000,
                            Title = 3
                        });
                });

            modelBuilder.Entity("GlowCare.Entities.Models.Procedure", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("AppointmentDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("ClientId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("EmployeeId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("Notes")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("ServiceId")
                        .HasColumnType("int");

                    b.Property<int?>("Status")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ClientId");

                    b.HasIndex("EmployeeId");

                    b.HasIndex("ServiceId");

                    b.ToTable("Procedures");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            AppointmentDate = new DateTime(2025, 9, 28, 10, 30, 0, 0, DateTimeKind.Unspecified),
                            ClientId = "1f4c1474-cf86-4199-9f6c-1f417b7ac9e4",
                            EmployeeId = "66e6b9a6-4c5a-4344-bdae-6edbacc4b608",
                            IsDeleted = false,
                            Notes = "First-time consultation, requested deep skin analysis.",
                            ServiceId = 5,
                            Status = 1
                        },
                        new
                        {
                            Id = 2,
                            AppointmentDate = new DateTime(2025, 9, 29, 14, 0, 0, 0, DateTimeKind.Unspecified),
                            ClientId = "1f4c1474-cf86-4199-9f6c-1f417b7ac9e4",
                            EmployeeId = "b75e8e37-95e4-44ef-a32c-10aebaff55b3",
                            IsDeleted = false,
                            Notes = "Follow-up massage therapy session.",
                            ServiceId = 6,
                            Status = 2
                        },
                        new
                        {
                            Id = 3,
                            AppointmentDate = new DateTime(2025, 10, 1, 9, 0, 0, 0, DateTimeKind.Unspecified),
                            ClientId = "1f4c1474-cf86-4199-9f6c-1f417b7ac9e4",
                            EmployeeId = "1dccdb69-fbd1-43c4-8c17-95796b5aa95e",
                            IsDeleted = false,
                            Notes = "Facial rejuvenation treatment scheduled.",
                            ServiceId = 8,
                            Status = 0
                        });
                });

            modelBuilder.Entity("GlowCare.Entities.Models.Review", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClientId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Comment")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("EmployeeId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("ProcedureId")
                        .HasColumnType("int");

                    b.Property<int?>("Rating")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ClientId");

                    b.HasIndex("EmployeeId");

                    b.HasIndex("ProcedureId");

                    b.ToTable("Reviews");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            ClientId = "1f4c1474-cf86-4199-9f6c-1f417b7ac9e4",
                            Comment = "Excellent service! The procedure was professional and I felt very comfortable.",
                            CreatedAt = new DateTime(2025, 12, 3, 8, 38, 10, 602, DateTimeKind.Utc).AddTicks(1749),
                            EmployeeId = "66e6b9a6-4c5a-4344-bdae-6edbacc4b608",
                            ProcedureId = 1,
                            Rating = 5
                        });
                });

            modelBuilder.Entity("GlowCare.Entities.Models.Schedule", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("EndTime")
                        .IsRequired()
                        .HasMaxLength(5)
                        .HasColumnType("nvarchar(5)");

                    b.Property<string>("StartTime")
                        .IsRequired()
                        .HasMaxLength(5)
                        .HasColumnType("nvarchar(5)");

                    b.HasKey("Id");

                    b.ToTable("Schedules");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            EndTime = "18:00",
                            StartTime = "09:00"
                        },
                        new
                        {
                            Id = 2,
                            EndTime = "16:00",
                            StartTime = "10:00"
                        },
                        new
                        {
                            Id = 3,
                            EndTime = "16:00",
                            StartTime = "9:00"
                        },
                        new
                        {
                            Id = 4,
                            EndTime = "15:00",
                            StartTime = "11:00"
                        });
                });

            modelBuilder.Entity("GlowCare.Entities.Models.ScheduleDayOfWeek", b =>
                {
                    b.Property<int>("DayOfWeekId")
                        .HasColumnType("int");

                    b.Property<int>("ScheduleId")
                        .HasColumnType("int");

                    b.HasKey("DayOfWeekId", "ScheduleId");

                    b.HasIndex("ScheduleId");

                    b.ToTable("SchedulesDaysOfWeek");

                    b.HasData(
                        new
                        {
                            DayOfWeekId = 5,
                            ScheduleId = 2
                        },
                        new
                        {
                            DayOfWeekId = 2,
                            ScheduleId = 3
                        },
                        new
                        {
                            DayOfWeekId = 4,
                            ScheduleId = 3
                        },
                        new
                        {
                            DayOfWeekId = 5,
                            ScheduleId = 4
                        },
                        new
                        {
                            DayOfWeekId = 6,
                            ScheduleId = 4
                        });
                });

            modelBuilder.Entity("GlowCare.Entities.Models.Service", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CategoryId")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("DurationInMinutes")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("nvarchar(80)");

                    b.Property<int>("Points")
                        .HasColumnType("int");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.ToTable("Services");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CategoryId = 1,
                            Description = "A relaxing facial treatment to cleanse, exfoliate, and nourish the skin, improving overall complexion and hydration.",
                            DurationInMinutes = 60,
                            Name = "Facial Treatment",
                            Points = 50,
                            Price = 50.00m
                        },
                        new
                        {
                            Id = 2,
                            CategoryId = 2,
                            Description = "Effective laser hair removal treatment for full legs, providing smooth, hair-free skin with minimal discomfort.",
                            DurationInMinutes = 90,
                            Name = "Laser Hair Removal - Full Legs",
                            Points = 120,
                            Price = 120.00m
                        },
                        new
                        {
                            Id = 3,
                            CategoryId = 3,
                            Description = "A full-body Swedish massage to relax muscles, improve circulation, and reduce stress.",
                            DurationInMinutes = 60,
                            Name = "Swedish Massage",
                            Points = 70,
                            Price = 70.00m
                        },
                        new
                        {
                            Id = 4,
                            CategoryId = 1,
                            Description = "A skin-resurfacing procedure that improves texture and tone by removing damaged outer layers of skin.",
                            DurationInMinutes = 45,
                            Name = "Chemical Peel",
                            Points = 80,
                            Price = 80.00m
                        },
                        new
                        {
                            Id = 5,
                            CategoryId = 1,
                            Description = "A minimally invasive exfoliation treatment that refreshes skin tone and reduces fine lines and scars.",
                            DurationInMinutes = 40,
                            Name = "Microdermabrasion",
                            Points = 70,
                            Price = 70m
                        },
                        new
                        {
                            Id = 6,
                            CategoryId = 4,
                            Description = "Botulinum toxin injections to reduce the appearance of fine lines and wrinkles by temporarily relaxing facial muscles.",
                            DurationInMinutes = 30,
                            Name = "Botox Injections",
                            Points = 250,
                            Price = 250.00m
                        },
                        new
                        {
                            Id = 7,
                            CategoryId = 4,
                            Description = "Injectable fillers to restore volume, smooth lines, and enhance facial contours.",
                            DurationInMinutes = 45,
                            Name = "Dermal Fillers",
                            Points = 300,
                            Price = 300.00m
                        },
                        new
                        {
                            Id = 8,
                            CategoryId = 2,
                            Description = "Quick and effective laser treatment for long-lasting hair reduction in the underarm area.",
                            DurationInMinutes = 20,
                            Name = "Laser Hair Removal - Underarms",
                            Points = 60,
                            Price = 60.00m
                        },
                        new
                        {
                            Id = 9,
                            CategoryId = 2,
                            Description = "Safe and precise laser hair removal for the bikini area, ensuring smooth and comfortable results.",
                            DurationInMinutes = 30,
                            Name = "Laser Hair Removal - Bikini Line",
                            Points = 80,
                            Price = 80.00m
                        },
                        new
                        {
                            Id = 10,
                            CategoryId = 2,
                            Description = "Laser hair removal treatment for both arms, providing smooth, hair-free skin with minimal discomfort.",
                            DurationInMinutes = 60,
                            Name = "Laser Hair Removal - Full Arms",
                            Points = 110,
                            Price = 110.00m
                        },
                        new
                        {
                            Id = 11,
                            CategoryId = 2,
                            Description = "Targeted laser treatment for facial hair, including upper lip, chin, and cheeks.",
                            DurationInMinutes = 30,
                            Name = "Laser Hair Removal - Face",
                            Points = 70,
                            Price = 70.00m
                        },
                        new
                        {
                            Id = 12,
                            CategoryId = 2,
                            Description = "Comprehensive laser hair removal treatment for the full back area.",
                            DurationInMinutes = 90,
                            Name = "Laser Hair Removal - Back",
                            Points = 150,
                            Price = 150.00m
                        },
                        new
                        {
                            Id = 13,
                            CategoryId = 2,
                            Description = "Complete full-body laser hair removal package for smooth, hair-free skin.",
                            DurationInMinutes = 180,
                            Name = "Laser Hair Removal - Full Body",
                            Points = 450,
                            Price = 450.00m
                        },
                        new
                        {
                            Id = 14,
                            CategoryId = 5,
                            Description = "A purifying facial designed to deeply cleanse, exfoliate, and remove impurities from the skin.",
                            DurationInMinutes = 60,
                            Name = "Deep Cleansing Facial",
                            Points = 65,
                            Price = 65.00m
                        },
                        new
                        {
                            Id = 15,
                            CategoryId = 5,
                            Description = "A rejuvenating treatment that targets fine lines and wrinkles, promoting firmer and youthful-looking skin.",
                            DurationInMinutes = 75,
                            Name = "Anti-Aging Facial",
                            Points = 120,
                            Price = 120.00m
                        },
                        new
                        {
                            Id = 16,
                            CategoryId = 5,
                            Description = "A specialized facial to reduce acne, clear clogged pores, and minimize inflammation with professional-grade products.",
                            DurationInMinutes = 70,
                            Name = "Acne Treatment Facial",
                            Points = 90,
                            Price = 90.00m
                        },
                        new
                        {
                            Id = 17,
                            CategoryId = 5,
                            Description = "A moisture-boosting facial designed to restore hydration, plumpness, and radiance to dry or dull skin.",
                            DurationInMinutes = 50,
                            Name = "Hydrating Facial",
                            Points = 75,
                            Price = 75.00m
                        },
                        new
                        {
                            Id = 18,
                            CategoryId = 5,
                            Description = "A skin-brightening treatment that reduces pigmentation, evens skin tone, and restores natural glow.",
                            DurationInMinutes = 60,
                            Name = "Brightening Facial",
                            Points = 95,
                            Price = 95.00m
                        },
                        new
                        {
                            Id = 19,
                            CategoryId = 5,
                            Description = "A treatment that boosts collagen production to improve elasticity and smoothness of the skin.",
                            DurationInMinutes = 70,
                            Name = "Collagen Facial",
                            Points = 140,
                            Price = 140.00m
                        },
                        new
                        {
                            Id = 20,
                            CategoryId = 3,
                            Description = "A relaxing massage using essential oils to reduce stress, improve mood, and promote overall well-being.",
                            DurationInMinutes = 60,
                            Name = "Aromatherapy Massage",
                            Points = 85,
                            Price = 85.00m
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("AspNetRoles", (string)null);

                    b.HasData(
                        new
                        {
                            Id = "1",
                            Name = "Admin",
                            NormalizedName = "ADMIN"
                        },
                        new
                        {
                            Id = "2",
                            Name = "User",
                            NormalizedName = "USER"
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("ProviderKey")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("RoleId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("LoginProvider")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("Name")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("GlowCare.Entities.Models.Certificate", b =>
                {
                    b.HasOne("GlowCare.Entities.Models.Employee", null)
                        .WithMany("Certificates")
                        .HasForeignKey("EmployeeId");
                });

            modelBuilder.Entity("GlowCare.Entities.Models.Client", b =>
                {
                    b.HasOne("GlowCare.Entities.Models.Membership", "Membership")
                        .WithMany("Clients")
                        .HasForeignKey("MembershipId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("GlowCare.Entities.Models.GlowUser", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Membership");

                    b.Navigation("User");
                });

            modelBuilder.Entity("GlowCare.Entities.Models.Employee", b =>
                {
                    b.HasOne("GlowCare.Entities.Models.GlowUser", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("GlowCare.Entities.Models.EmployeeSchedule", b =>
                {
                    b.HasOne("GlowCare.Entities.Models.Employee", "Employee")
                        .WithMany()
                        .HasForeignKey("EmployeeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("GlowCare.Entities.Models.Schedule", "Schedule")
                        .WithMany("EmployeesSchedules")
                        .HasForeignKey("ScheduleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Employee");

                    b.Navigation("Schedule");
                });

            modelBuilder.Entity("GlowCare.Entities.Models.EmployeeService", b =>
                {
                    b.HasOne("GlowCare.Entities.Models.Employee", "Employee")
                        .WithMany()
                        .HasForeignKey("EmployeeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("GlowCare.Entities.Models.Service", "Service")
                        .WithMany()
                        .HasForeignKey("ServiceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Employee");

                    b.Navigation("Service");
                });

            modelBuilder.Entity("GlowCare.Entities.Models.Procedure", b =>
                {
                    b.HasOne("GlowCare.Entities.Models.Client", "Client")
                        .WithMany("Procedures")
                        .HasForeignKey("ClientId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("GlowCare.Entities.Models.Employee", "Employee")
                        .WithMany("Procedures")
                        .HasForeignKey("EmployeeId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("GlowCare.Entities.Models.Service", "Service")
                        .WithMany("Procedures")
                        .HasForeignKey("ServiceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Client");

                    b.Navigation("Employee");

                    b.Navigation("Service");
                });

            modelBuilder.Entity("GlowCare.Entities.Models.Review", b =>
                {
                    b.HasOne("GlowCare.Entities.Models.Client", "Client")
                        .WithMany("Reviews")
                        .HasForeignKey("ClientId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("GlowCare.Entities.Models.Employee", "Employee")
                        .WithMany("Reviews")
                        .HasForeignKey("EmployeeId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("GlowCare.Entities.Models.Procedure", "Procedure")
                        .WithMany("Reviews")
                        .HasForeignKey("ProcedureId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Client");

                    b.Navigation("Employee");

                    b.Navigation("Procedure");
                });

            modelBuilder.Entity("GlowCare.Entities.Models.ScheduleDayOfWeek", b =>
                {
                    b.HasOne("GlowCare.Entities.Models.DayOfWeek", "DayOfWeek")
                        .WithMany("ScheduleDaysOfWeek")
                        .HasForeignKey("DayOfWeekId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("GlowCare.Entities.Models.Schedule", "Schedule")
                        .WithMany("ScheduleDaysOfWeek")
                        .HasForeignKey("ScheduleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("DayOfWeek");

                    b.Navigation("Schedule");
                });

            modelBuilder.Entity("GlowCare.Entities.Models.Service", b =>
                {
                    b.HasOne("GlowCare.Entities.Models.Category", "Category")
                        .WithMany()
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Category");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("GlowCare.Entities.Models.GlowUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("GlowCare.Entities.Models.GlowUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("GlowCare.Entities.Models.GlowUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("GlowCare.Entities.Models.GlowUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("GlowCare.Entities.Models.Client", b =>
                {
                    b.Navigation("Procedures");

                    b.Navigation("Reviews");
                });

            modelBuilder.Entity("GlowCare.Entities.Models.DayOfWeek", b =>
                {
                    b.Navigation("ScheduleDaysOfWeek");
                });

            modelBuilder.Entity("GlowCare.Entities.Models.Employee", b =>
                {
                    b.Navigation("Certificates");

                    b.Navigation("Procedures");

                    b.Navigation("Reviews");
                });

            modelBuilder.Entity("GlowCare.Entities.Models.Membership", b =>
                {
                    b.Navigation("Clients");
                });

            modelBuilder.Entity("GlowCare.Entities.Models.Procedure", b =>
                {
                    b.Navigation("Reviews");
                });

            modelBuilder.Entity("GlowCare.Entities.Models.Schedule", b =>
                {
                    b.Navigation("EmployeesSchedules");

                    b.Navigation("ScheduleDaysOfWeek");
                });

            modelBuilder.Entity("GlowCare.Entities.Models.Service", b =>
                {
                    b.Navigation("Procedures");
                });
#pragma warning restore 612, 618
        }
    }
}
