// <auto-generated />
using System;
using GlowCare.Entities;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace GlowCare.Entities.Migrations
{
    [DbContext(typeof(GlowCareDbContext))]
    partial class GlowCareDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("GlowCare.Entities.Models.Category", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.HasKey("Id");

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Грижа за кожата"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Лазерни процедури"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Масаж"
                        },
                        new
                        {
                            Id = 4,
                            Name = "Естетична медицина"
                        },
                        new
                        {
                            Id = 5,
                            Name = "Процедури за лице"
                        });
                });

            modelBuilder.Entity("GlowCare.Entities.Models.Employee", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Biography")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("ExperienceYears")
                        .HasColumnType("int");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("Occupation")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("Employees");

                    b.HasData(
                        new
                        {
                            Id = new Guid("66e6b9a6-4c5a-4344-bdae-6edbacc4b608"),
                            Biography = "Аз съм лицензиран дерматолог с 5 години опит в подпомагането на пациентите да постигнат по-здрава кожа. Моята експертиза включва лечение на състояния като акне, екзема и пигментни нарушения, както и извършване на съвременни лазерни и козметични процедури. Стремя се да информирам пациентите си и да създавам персонализирани терапевтични планове, които съчетават доказани медицински методи с модерни иновации в грижата за кожата.",
                            ExperienceYears = 5,
                            IsDeleted = false,
                            Occupation = "Дерматолог",
                            UserId = new Guid("a7d3c5e2-9b41-4f12-8f34-123456789abc")
                        },
                        new
                        {
                            Id = new Guid("b75e8e37-95e4-44ef-a32c-10aebaff55b3"),
                            Biography = "Аз съм сертифициран естетик с 10 години опит в предоставянето на процедури за грижа за кожата, терапии за лице и анти-ейдж терапии. Моята цел е да помогна на клиентите да постигнат сияйна и здрава кожа чрез съчетание на съвременни техники и натурални методи.",
                            ExperienceYears = 10,
                            IsDeleted = false,
                            Occupation = "Естетик",
                            UserId = new Guid("ac31b0bb-d05a-438d-be06-9bfe3323cf08")
                        },
                        new
                        {
                            Id = new Guid("1dccdb69-fbd1-43c4-8c17-95796b5aa95e"),
                            Biography = "Аз съм лицензиран специалист по лазерни процедури с 7 години опит в лазерната епилация, премахването на татуировки и процедурите за обновяване на кожата. Фокусът ми е върху това да предоставям безопасни, ефективни и индивидуално съобразени решения за всеки клиент с цел постигане на гладка и здрава кожа.",
                            ExperienceYears = 6,
                            IsDeleted = false,
                            Occupation = "Лазерен специалист",
                            UserId = new Guid("29965aaa-46cf-4829-93b8-e38401be7547")
                        },
                        new
                        {
                            Id = new Guid("a0617bdf-80af-4316-a9c9-c2fd77170f7f"),
                            Biography = "Аз съм сертифициран масажист с 6 години опит в шведския, дълбокотъканния и лечебния масаж. Моята цел е да помогна на клиентите да се отпуснат, да облекчат стреса и да подобрят общото си благосъстояние чрез персонализирани процедури.",
                            ExperienceYears = 6,
                            IsDeleted = false,
                            Occupation = "Масажист",
                            UserId = new Guid("c9f4e7b1-2d33-4a11-8f56-abcdef123456")
                        });
                });

            modelBuilder.Entity("GlowCare.Entities.Models.EmployeeService", b =>
                {
                    b.Property<Guid>("EmployeeId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("ServiceId")
                        .HasColumnType("int");

                    b.HasKey("EmployeeId", "ServiceId");

                    b.HasIndex("ServiceId");

                    b.ToTable("EmployeesServices");

                    b.HasData(
                        new
                        {
                            EmployeeId = new Guid("66e6b9a6-4c5a-4344-bdae-6edbacc4b608"),
                            ServiceId = 1
                        },
                        new
                        {
                            EmployeeId = new Guid("66e6b9a6-4c5a-4344-bdae-6edbacc4b608"),
                            ServiceId = 4
                        },
                        new
                        {
                            EmployeeId = new Guid("66e6b9a6-4c5a-4344-bdae-6edbacc4b608"),
                            ServiceId = 5
                        },
                        new
                        {
                            EmployeeId = new Guid("66e6b9a6-4c5a-4344-bdae-6edbacc4b608"),
                            ServiceId = 6
                        },
                        new
                        {
                            EmployeeId = new Guid("66e6b9a6-4c5a-4344-bdae-6edbacc4b608"),
                            ServiceId = 14
                        },
                        new
                        {
                            EmployeeId = new Guid("66e6b9a6-4c5a-4344-bdae-6edbacc4b608"),
                            ServiceId = 15
                        },
                        new
                        {
                            EmployeeId = new Guid("66e6b9a6-4c5a-4344-bdae-6edbacc4b608"),
                            ServiceId = 16
                        },
                        new
                        {
                            EmployeeId = new Guid("66e6b9a6-4c5a-4344-bdae-6edbacc4b608"),
                            ServiceId = 17
                        },
                        new
                        {
                            EmployeeId = new Guid("66e6b9a6-4c5a-4344-bdae-6edbacc4b608"),
                            ServiceId = 18
                        },
                        new
                        {
                            EmployeeId = new Guid("b75e8e37-95e4-44ef-a32c-10aebaff55b3"),
                            ServiceId = 6
                        },
                        new
                        {
                            EmployeeId = new Guid("b75e8e37-95e4-44ef-a32c-10aebaff55b3"),
                            ServiceId = 7
                        },
                        new
                        {
                            EmployeeId = new Guid("1dccdb69-fbd1-43c4-8c17-95796b5aa95e"),
                            ServiceId = 2
                        },
                        new
                        {
                            EmployeeId = new Guid("1dccdb69-fbd1-43c4-8c17-95796b5aa95e"),
                            ServiceId = 8
                        },
                        new
                        {
                            EmployeeId = new Guid("1dccdb69-fbd1-43c4-8c17-95796b5aa95e"),
                            ServiceId = 9
                        },
                        new
                        {
                            EmployeeId = new Guid("1dccdb69-fbd1-43c4-8c17-95796b5aa95e"),
                            ServiceId = 10
                        },
                        new
                        {
                            EmployeeId = new Guid("1dccdb69-fbd1-43c4-8c17-95796b5aa95e"),
                            ServiceId = 11
                        },
                        new
                        {
                            EmployeeId = new Guid("1dccdb69-fbd1-43c4-8c17-95796b5aa95e"),
                            ServiceId = 12
                        },
                        new
                        {
                            EmployeeId = new Guid("b75e8e37-95e4-44ef-a32c-10aebaff55b3"),
                            ServiceId = 13
                        },
                        new
                        {
                            EmployeeId = new Guid("a0617bdf-80af-4316-a9c9-c2fd77170f7f"),
                            ServiceId = 3
                        },
                        new
                        {
                            EmployeeId = new Guid("a0617bdf-80af-4316-a9c9-c2fd77170f7f"),
                            ServiceId = 20
                        });
                });

            modelBuilder.Entity("GlowCare.Entities.Models.GlowUser", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<int>("Age")
                        .HasColumnType("int");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("Gender")
                        .HasColumnType("int");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<bool>("IsSpecialist")
                        .HasColumnType("bit");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<int>("LoyaltyPoints")
                        .HasColumnType("int");

                    b.Property<int?>("MembershipId")
                        .HasColumnType("int");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("MembershipId");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.ToTable("AspNetUsers", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("a7d3c5e2-9b41-4f12-8f34-123456789abc"),
                            AccessFailedCount = 0,
                            Age = 32,
                            ConcurrencyStamp = "07d25f01-496f-4338-a289-80d20a55ff46",
                            Email = "elena.dimitrova@gmail.com",
                            EmailConfirmed = true,
                            FirstName = "Елена",
                            Gender = 1,
                            IsDeleted = false,
                            IsSpecialist = true,
                            LastName = "Димитрова",
                            LockoutEnabled = false,
                            LoyaltyPoints = 0,
                            NormalizedEmail = "ELENA.DIMITROVA@GMAIL.COM",
                            NormalizedUserName = "ELENA.DIMITROVA",
                            PasswordHash = "AQAAAAIAAYagAAAAEAwB9Urfs/3/yau1Id5TvThbqZQHOjE6Crdc/3aJUYW1zGfI8f+yaQASRPpwQgHy5w==",
                            PhoneNumber = "0888123456",
                            PhoneNumberConfirmed = true,
                            SecurityStamp = "bfb94cc6-d1c4-4315-8f5e-f1d3535f4c01",
                            TwoFactorEnabled = false,
                            UserName = "elena.dimitrova"
                        },
                        new
                        {
                            Id = new Guid("ac31b0bb-d05a-438d-be06-9bfe3323cf08"),
                            AccessFailedCount = 0,
                            Age = 30,
                            ConcurrencyStamp = "8f657107-c426-45ba-95b1-9d50d864e0ab",
                            Email = "johndoe@gmail.com",
                            EmailConfirmed = true,
                            FirstName = "Джон",
                            Gender = 0,
                            IsDeleted = false,
                            IsSpecialist = true,
                            LastName = "Доу",
                            LockoutEnabled = false,
                            LoyaltyPoints = 0,
                            NormalizedEmail = "JOHNDOE@GMAIL.COM",
                            NormalizedUserName = "JOHN.DOE",
                            PasswordHash = "AQAAAAIAAYagAAAAEHRk2lkJyn7P8OkZzh8zpgcHFnx4YmHJLcZFgAJ22/UxO4GldMfjC1PN+vyrvsPCbQ==",
                            PhoneNumber = "0875757574",
                            PhoneNumberConfirmed = true,
                            SecurityStamp = "a6241046-575b-4a3f-a668-c6aa755a232f",
                            TwoFactorEnabled = false,
                            UserName = "john.doe"
                        },
                        new
                        {
                            Id = new Guid("29965aaa-46cf-4829-93b8-e38401be7547"),
                            AccessFailedCount = 0,
                            Age = 38,
                            ConcurrencyStamp = "7ceacac6-fa4d-4db9-ad6b-d28033f4c114",
                            Email = "maria.petrova@gmail.com",
                            EmailConfirmed = true,
                            FirstName = "Мария",
                            Gender = 1,
                            IsDeleted = false,
                            IsSpecialist = true,
                            LastName = "Петрова",
                            LockoutEnabled = false,
                            LoyaltyPoints = 0,
                            NormalizedEmail = "MARIA.PETROVA@GMAIL.COM",
                            NormalizedUserName = "MARIA.PETROVA",
                            PasswordHash = "AQAAAAIAAYagAAAAEHtASgpdhVbCPi/j0Ik5a1C7NSxcXqLAl3Wbtt/DA1vN+J7lUv162Kv4BPYSIyV/gw==",
                            PhoneNumber = "0899123456",
                            PhoneNumberConfirmed = true,
                            SecurityStamp = "68e7add5-6f2f-4792-a2e6-01f596c74a52",
                            TwoFactorEnabled = false,
                            UserName = "maria.petrova"
                        },
                        new
                        {
                            Id = new Guid("c9f4e7b1-2d33-4a11-8f56-abcdef123456"),
                            AccessFailedCount = 0,
                            Age = 30,
                            ConcurrencyStamp = "b5efc2d7-5be7-4fc5-b8a6-f1f935fdacf6",
                            Email = "ivana.koleva@gmail.com",
                            EmailConfirmed = true,
                            FirstName = "Ивана",
                            Gender = 1,
                            IsDeleted = false,
                            IsSpecialist = true,
                            LastName = "Колева",
                            LockoutEnabled = false,
                            LoyaltyPoints = 0,
                            NormalizedEmail = "IVANA.KOLEVA@GMAIL.COM",
                            NormalizedUserName = "IVANA.KOLEVA",
                            PasswordHash = "AQAAAAIAAYagAAAAEPgxfSzNx9r6tRQlx8puCDiRpdh1JB+gjQXbI1BCcSf2Avuu+nVdEy8wg12I2i0lcw==",
                            PhoneNumber = "0888234567",
                            PhoneNumberConfirmed = true,
                            SecurityStamp = "e0ff1671-f59e-407c-a1bc-b6034b44ac41",
                            TwoFactorEnabled = false,
                            UserName = "ivana.koleva"
                        },
                        new
                        {
                            Id = new Guid("e5c2a9b3-4a67-4f89-8d23-556677889900"),
                            AccessFailedCount = 0,
                            Age = 30,
                            ConcurrencyStamp = "90243b04-1bad-480a-a2de-cf7657d834cc",
                            Email = "nikol.georgieva@gmail.com",
                            EmailConfirmed = true,
                            FirstName = "Никол",
                            Gender = 1,
                            IsDeleted = false,
                            IsSpecialist = false,
                            LastName = "Георгиева",
                            LockoutEnabled = false,
                            LoyaltyPoints = 0,
                            MembershipId = 1,
                            NormalizedEmail = "NIKOL.GEORGIEVA@GMAIL.COM",
                            NormalizedUserName = "NIKOL.GEORGIEVA",
                            PasswordHash = "AQAAAAIAAYagAAAAEB/fGKTHK1tFb2GdHT3m/+acY9RceL8aGHhACaRP6qN1WDJuDTrii/8hpNGCmH3LKA==",
                            PhoneNumber = "0855123456",
                            PhoneNumberConfirmed = true,
                            SecurityStamp = "e9c2550f-30cc-4116-a85c-20265258d5a5",
                            TwoFactorEnabled = false,
                            UserName = "nikol.georgieva"
                        },
                        new
                        {
                            Id = new Guid("fc95b3fa-f342-4172-ac8b-5b35951ad760"),
                            AccessFailedCount = 0,
                            Age = 18,
                            ConcurrencyStamp = "fe2a9ea6-fde8-4113-a3fb-814f3b9174a2",
                            Email = "teodora_nedkova@abv.bg",
                            EmailConfirmed = true,
                            FirstName = "Теодора",
                            Gender = 1,
                            IsDeleted = false,
                            IsSpecialist = false,
                            LastName = "Недкова",
                            LockoutEnabled = false,
                            LoyaltyPoints = 0,
                            NormalizedEmail = "TEODORA_NEDKOVA@ABV.BG",
                            NormalizedUserName = "TEODORA.NEDKOVA",
                            PasswordHash = "AQAAAAIAAYagAAAAENBNeMEjSBv+XaO23n5PqLCx2DF0sbqo+EnXbC+2P2AopNubu5Oz0PMpsd2z3jxeIw==",
                            PhoneNumber = "0878654562",
                            PhoneNumberConfirmed = true,
                            SecurityStamp = "258513a82f1147ba92a0e43f1602b7c3",
                            TwoFactorEnabled = false,
                            UserName = "teodora.nedkova"
                        });
                });

            modelBuilder.Entity("GlowCare.Entities.Models.Membership", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("DiscountPercentage")
                        .HasColumnType("int");

                    b.Property<int>("Points")
                        .HasColumnType("int");

                    b.Property<int>("Title")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Memberships");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            DiscountPercentage = 20,
                            Points = 0,
                            Title = 0
                        },
                        new
                        {
                            Id = 2,
                            DiscountPercentage = 10,
                            Points = 500,
                            Title = 1
                        },
                        new
                        {
                            Id = 3,
                            DiscountPercentage = 15,
                            Points = 1000,
                            Title = 2
                        },
                        new
                        {
                            Id = 4,
                            DiscountPercentage = 20,
                            Points = 2000,
                            Title = 3
                        });
                });

            modelBuilder.Entity("GlowCare.Entities.Models.Procedure", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("AppointmentDate")
                        .HasColumnType("datetime2");

                    b.Property<int?>("CancelledBy")
                        .HasColumnType("int");

                    b.Property<Guid>("EmployeeId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("Notes")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("RewardPointsGranted")
                        .HasColumnType("bit");

                    b.Property<int>("ServiceId")
                        .HasColumnType("int");

                    b.Property<int?>("Status")
                        .HasColumnType("int");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("EmployeeId");

                    b.HasIndex("ServiceId");

                    b.HasIndex("UserId");

                    b.ToTable("Procedures");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            AppointmentDate = new DateTime(2025, 9, 28, 10, 30, 0, 0, DateTimeKind.Unspecified),
                            EmployeeId = new Guid("66e6b9a6-4c5a-4344-bdae-6edbacc4b608"),
                            IsDeleted = false,
                            Notes = "Първоначална консултация, заявен е задълбочен анализ на кожата.",
                            RewardPointsGranted = false,
                            ServiceId = 5,
                            Status = 1,
                            UserId = new Guid("e5c2a9b3-4a67-4f89-8d23-556677889900")
                        },
                        new
                        {
                            Id = 2,
                            AppointmentDate = new DateTime(2025, 9, 29, 14, 0, 0, 0, DateTimeKind.Unspecified),
                            EmployeeId = new Guid("b75e8e37-95e4-44ef-a32c-10aebaff55b3"),
                            IsDeleted = false,
                            Notes = "Последваща сесия за масажна терапия.",
                            RewardPointsGranted = false,
                            ServiceId = 6,
                            Status = 2,
                            UserId = new Guid("fc95b3fa-f342-4172-ac8b-5b35951ad760")
                        },
                        new
                        {
                            Id = 3,
                            AppointmentDate = new DateTime(2025, 10, 1, 9, 0, 0, 0, DateTimeKind.Unspecified),
                            EmployeeId = new Guid("1dccdb69-fbd1-43c4-8c17-95796b5aa95e"),
                            IsDeleted = false,
                            Notes = "Планирана е процедура за подмладяване на лицето.",
                            RewardPointsGranted = false,
                            ServiceId = 8,
                            Status = 0,
                            UserId = new Guid("fc95b3fa-f342-4172-ac8b-5b35951ad760")
                        });
                });

            modelBuilder.Entity("GlowCare.Entities.Models.Review", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Comment")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("EmployeeId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<int?>("ProcedureId")
                        .HasColumnType("int");

                    b.Property<int>("Rating")
                        .HasColumnType("int");

                    b.Property<int>("ServiceId")
                        .HasColumnType("int");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("EmployeeId");

                    b.HasIndex("ProcedureId");

                    b.HasIndex("ServiceId");

                    b.HasIndex("UserId");

                    b.ToTable("Reviews");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Comment = "Отлично обслужване! Процедурата беше извършена професионално и се чувствах много комфортно.",
                            CreatedAt = new DateTime(2026, 4, 22, 19, 36, 25, 742, DateTimeKind.Utc).AddTicks(9032),
                            EmployeeId = new Guid("66e6b9a6-4c5a-4344-bdae-6edbacc4b608"),
                            IsDeleted = false,
                            ProcedureId = 1,
                            Rating = 5,
                            ServiceId = 5,
                            UserId = new Guid("fc95b3fa-f342-4172-ac8b-5b35951ad760")
                        });
                });

            modelBuilder.Entity("GlowCare.Entities.Models.Schedule", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("DayOfWeek")
                        .HasColumnType("int");

                    b.Property<Guid>("EmployeeId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("EndTime")
                        .IsRequired()
                        .HasMaxLength(5)
                        .HasColumnType("nvarchar(5)");

                    b.Property<string>("StartTime")
                        .IsRequired()
                        .HasMaxLength(5)
                        .HasColumnType("nvarchar(5)");

                    b.HasKey("Id");

                    b.HasIndex("EmployeeId");

                    b.ToTable("Schedules");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            DayOfWeek = 1,
                            EmployeeId = new Guid("66e6b9a6-4c5a-4344-bdae-6edbacc4b608"),
                            EndTime = "16:00",
                            StartTime = "10:00"
                        },
                        new
                        {
                            Id = 2,
                            DayOfWeek = 2,
                            EmployeeId = new Guid("66e6b9a6-4c5a-4344-bdae-6edbacc4b608"),
                            EndTime = "16:00",
                            StartTime = "09:00"
                        },
                        new
                        {
                            Id = 3,
                            DayOfWeek = 3,
                            EmployeeId = new Guid("66e6b9a6-4c5a-4344-bdae-6edbacc4b608"),
                            EndTime = "16:00",
                            StartTime = "10:00"
                        },
                        new
                        {
                            Id = 4,
                            DayOfWeek = 4,
                            EmployeeId = new Guid("66e6b9a6-4c5a-4344-bdae-6edbacc4b608"),
                            EndTime = "16:00",
                            StartTime = "09:00"
                        },
                        new
                        {
                            Id = 5,
                            DayOfWeek = 5,
                            EmployeeId = new Guid("66e6b9a6-4c5a-4344-bdae-6edbacc4b608"),
                            EndTime = "16:00",
                            StartTime = "10:00"
                        },
                        new
                        {
                            Id = 6,
                            DayOfWeek = 1,
                            EmployeeId = new Guid("b75e8e37-95e4-44ef-a32c-10aebaff55b3"),
                            EndTime = "18:00",
                            StartTime = "09:00"
                        },
                        new
                        {
                            Id = 7,
                            DayOfWeek = 2,
                            EmployeeId = new Guid("b75e8e37-95e4-44ef-a32c-10aebaff55b3"),
                            EndTime = "16:00",
                            StartTime = "09:00"
                        },
                        new
                        {
                            Id = 8,
                            DayOfWeek = 3,
                            EmployeeId = new Guid("b75e8e37-95e4-44ef-a32c-10aebaff55b3"),
                            EndTime = "18:00",
                            StartTime = "09:00"
                        },
                        new
                        {
                            Id = 9,
                            DayOfWeek = 4,
                            EmployeeId = new Guid("b75e8e37-95e4-44ef-a32c-10aebaff55b3"),
                            EndTime = "18:00",
                            StartTime = "09:00"
                        },
                        new
                        {
                            Id = 10,
                            DayOfWeek = 5,
                            EmployeeId = new Guid("b75e8e37-95e4-44ef-a32c-10aebaff55b3"),
                            EndTime = "16:00",
                            StartTime = "09:00"
                        },
                        new
                        {
                            Id = 11,
                            DayOfWeek = 1,
                            EmployeeId = new Guid("1dccdb69-fbd1-43c4-8c17-95796b5aa95e"),
                            EndTime = "17:00",
                            StartTime = "11:00"
                        },
                        new
                        {
                            Id = 12,
                            DayOfWeek = 2,
                            EmployeeId = new Guid("1dccdb69-fbd1-43c4-8c17-95796b5aa95e"),
                            EndTime = "17:00",
                            StartTime = "11:00"
                        },
                        new
                        {
                            Id = 13,
                            DayOfWeek = 3,
                            EmployeeId = new Guid("1dccdb69-fbd1-43c4-8c17-95796b5aa95e"),
                            EndTime = "17:00",
                            StartTime = "11:00"
                        },
                        new
                        {
                            Id = 14,
                            DayOfWeek = 4,
                            EmployeeId = new Guid("1dccdb69-fbd1-43c4-8c17-95796b5aa95e"),
                            EndTime = "17:00",
                            StartTime = "11:00"
                        },
                        new
                        {
                            Id = 15,
                            DayOfWeek = 5,
                            EmployeeId = new Guid("1dccdb69-fbd1-43c4-8c17-95796b5aa95e"),
                            EndTime = "17:00",
                            StartTime = "11:00"
                        },
                        new
                        {
                            Id = 16,
                            DayOfWeek = 1,
                            EmployeeId = new Guid("a0617bdf-80af-4316-a9c9-c2fd77170f7f"),
                            EndTime = "18:00",
                            StartTime = "12:00"
                        },
                        new
                        {
                            Id = 17,
                            DayOfWeek = 3,
                            EmployeeId = new Guid("a0617bdf-80af-4316-a9c9-c2fd77170f7f"),
                            EndTime = "18:00",
                            StartTime = "12:00"
                        },
                        new
                        {
                            Id = 18,
                            DayOfWeek = 5,
                            EmployeeId = new Guid("a0617bdf-80af-4316-a9c9-c2fd77170f7f"),
                            EndTime = "18:00",
                            StartTime = "12:00"
                        });
                });

            modelBuilder.Entity("GlowCare.Entities.Models.Service", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CategoryId")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("DurationInMinutes")
                        .HasColumnType("int");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("nvarchar(80)");

                    b.Property<int>("Points")
                        .HasColumnType("int");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.ToTable("Services");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CategoryId = 1,
                            Description = "Релаксираща терапия за лице, която почиства, ексфолира и подхранва кожата, като подобрява нейния вид и хидратация.",
                            DurationInMinutes = 60,
                            IsDeleted = false,
                            Name = "Терапия за лице",
                            Points = 50,
                            Price = 50.0m
                        },
                        new
                        {
                            Id = 2,
                            CategoryId = 2,
                            Description = "Ефективна лазерна епилация за цели крака, която осигурява гладка кожа без окосмяване с минимален дискомфорт.",
                            DurationInMinutes = 90,
                            IsDeleted = false,
                            Name = "Лазерна епилация - цели крака",
                            Points = 120,
                            Price = 120.0m
                        },
                        new
                        {
                            Id = 3,
                            CategoryId = 3,
                            Description = "Шведски масаж на цяло тяло за отпускане на мускулите, подобряване на кръвообращението и намаляване на стреса.",
                            DurationInMinutes = 60,
                            IsDeleted = false,
                            Name = "Шведски масаж",
                            Points = 70,
                            Price = 70.0m
                        },
                        new
                        {
                            Id = 4,
                            CategoryId = 1,
                            Description = "Процедура за обновяване на кожата, която подобрява текстурата и тена чрез премахване на увредените външни слоеве.",
                            DurationInMinutes = 45,
                            IsDeleted = false,
                            Name = "Химичен пилинг",
                            Points = 80,
                            Price = 80.0m
                        },
                        new
                        {
                            Id = 5,
                            CategoryId = 1,
                            Description = "Минимално инвазивна ексфолираща процедура, която освежава тена и намалява фините линии и белезите.",
                            DurationInMinutes = 40,
                            IsDeleted = false,
                            Name = "Микродермабразио",
                            Points = 70,
                            Price = 70m
                        },
                        new
                        {
                            Id = 6,
                            CategoryId = 4,
                            Description = "Инжекции с ботулинов токсин за намаляване на фините линии и бръчките чрез временно отпускане на лицевите мускули.",
                            DurationInMinutes = 30,
                            IsDeleted = false,
                            Name = "Ботокс инжекции",
                            Points = 250,
                            Price = 250.0m
                        },
                        new
                        {
                            Id = 7,
                            CategoryId = 4,
                            Description = "Инжекционни филъри за възстановяване на обема, изглаждане на линиите и подчертаване на контурите на лицето.",
                            DurationInMinutes = 45,
                            IsDeleted = false,
                            Name = "Дермални филъри",
                            Points = 300,
                            Price = 300.0m
                        },
                        new
                        {
                            Id = 8,
                            CategoryId = 2,
                            Description = "Бърза и ефективна лазерна процедура за дълготрайно намаляване на окосмяването в областта на подмишниците.",
                            DurationInMinutes = 20,
                            IsDeleted = false,
                            Name = "Лазерна епилация - подмишници",
                            Points = 60,
                            Price = 60.0m
                        },
                        new
                        {
                            Id = 9,
                            CategoryId = 2,
                            Description = "Безопасна и прецизна лазерна епилация за бикини зоната, осигуряваща гладки и комфортни резултати.",
                            DurationInMinutes = 30,
                            IsDeleted = false,
                            Name = "Лазерна епилация - бикини зона",
                            Points = 80,
                            Price = 80.0m
                        },
                        new
                        {
                            Id = 10,
                            CategoryId = 2,
                            Description = "Лазерна епилация за двете ръце, осигуряваща гладка кожа без окосмяване с минимален дискомфорт.",
                            DurationInMinutes = 60,
                            IsDeleted = false,
                            Name = "Лазерна епилация - цели ръце",
                            Points = 110,
                            Price = 110.0m
                        },
                        new
                        {
                            Id = 11,
                            CategoryId = 2,
                            Description = "Целенасочена лазерна процедура за лицево окосмяване, включително горна устна, брадичка и бузи.",
                            DurationInMinutes = 30,
                            IsDeleted = false,
                            Name = "Лазерна епилация - лице",
                            Points = 70,
                            Price = 70.0m
                        },
                        new
                        {
                            Id = 12,
                            CategoryId = 2,
                            Description = "Комплексна лазерна епилация за цялата зона на гърба.",
                            DurationInMinutes = 90,
                            IsDeleted = false,
                            Name = "Лазерна епилация - гръб",
                            Points = 150,
                            Price = 150.0m
                        },
                        new
                        {
                            Id = 13,
                            CategoryId = 2,
                            Description = "Пълен пакет за лазерна епилация на цяло тяло за гладка кожа без окосмяване.",
                            DurationInMinutes = 180,
                            IsDeleted = false,
                            Name = "Лазерна епилация - цяло тяло",
                            Points = 450,
                            Price = 450.0m
                        },
                        new
                        {
                            Id = 14,
                            CategoryId = 5,
                            Description = "Почистваща терапия за лице, създадена за дълбоко почистване, ексфолиране и премахване на замърсяванията от кожата.",
                            DurationInMinutes = 60,
                            IsDeleted = false,
                            Name = "Дълбоко почистваща терапия за лице",
                            Points = 65,
                            Price = 65.0m
                        },
                        new
                        {
                            Id = 15,
                            CategoryId = 5,
                            Description = "Подмладяваща процедура, насочена към фините линии и бръчките, която подпомага по-стегнат и младежки вид на кожата.",
                            DurationInMinutes = 75,
                            IsDeleted = false,
                            Name = "Анти-ейдж терапия за лице",
                            Points = 120,
                            Price = 120.0m
                        },
                        new
                        {
                            Id = 16,
                            CategoryId = 5,
                            Description = "Специализирана терапия за лице за намаляване на акнето, почистване на запушените пори и ограничаване на възпалението с професионални продукти.",
                            DurationInMinutes = 70,
                            IsDeleted = false,
                            Name = "Терапия за лице против акне",
                            Points = 90,
                            Price = 90.0m
                        },
                        new
                        {
                            Id = 17,
                            CategoryId = 5,
                            Description = "Хидратираща терапия за лице, създадена да възстанови влагата, плътността и сиянието на суха или повяхнала кожа.",
                            DurationInMinutes = 50,
                            IsDeleted = false,
                            Name = "Хидратираща терапия за лице",
                            Points = 75,
                            Price = 75.0m
                        },
                        new
                        {
                            Id = 18,
                            CategoryId = 5,
                            Description = "Изсветляваща процедура, която намалява пигментацията, изравнява тена и възстановява естествения блясък на кожата.",
                            DurationInMinutes = 60,
                            IsDeleted = false,
                            Name = "Изсветляваща терапия за лице",
                            Points = 95,
                            Price = 95.0m
                        },
                        new
                        {
                            Id = 19,
                            CategoryId = 5,
                            Description = "Процедура, която стимулира производството на колаген за подобряване на еластичността и гладкостта на кожата.",
                            DurationInMinutes = 70,
                            IsDeleted = false,
                            Name = "Колагенова терапия за лице",
                            Points = 140,
                            Price = 140.0m
                        },
                        new
                        {
                            Id = 20,
                            CategoryId = 3,
                            Description = "Релаксиращ масаж с етерични масла за намаляване на стреса, подобряване на настроението и насърчаване на общото благосъстояние.",
                            DurationInMinutes = 60,
                            IsDeleted = false,
                            Name = "Ароматерапевтичен масаж",
                            Points = 85,
                            Price = 85.0m
                        });
                });

            modelBuilder.Entity("GlowCare.Entities.Models.SpecialistApplication", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Biography")
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.Property<DateTime>("CreatedOn")
                        .HasColumnType("datetime2");

                    b.Property<int>("ExperienceYears")
                        .HasColumnType("int");

                    b.Property<string>("Occupation")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RejectionReason")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("SpecialistApplication");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole<System.Guid>", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("AspNetRoles", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("8c384109-e13f-4556-a810-ab9ba28161a2"),
                            ConcurrencyStamp = "a1111111-1111-1111-1111-111111111111",
                            Name = "Admin",
                            NormalizedName = "ADMIN"
                        },
                        new
                        {
                            Id = new Guid("5dcbdb75-d5c9-4109-ab52-fd869be79532"),
                            ConcurrencyStamp = "b2222222-2222-2222-2222-222222222222",
                            Name = "User",
                            NormalizedName = "USER"
                        },
                        new
                        {
                            Id = new Guid("a3f06ed0-4bca-4e98-8bef-4cd91e64e2a1"),
                            ConcurrencyStamp = "c3333333-3333-3333-3333-333333333333",
                            Name = "Specialist",
                            NormalizedName = "SPECIALIST"
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<System.Guid>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("RoleId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<System.Guid>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<System.Guid>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("ProviderKey")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<System.Guid>", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("RoleId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);

                    b.HasData(
                        new
                        {
                            UserId = new Guid("c9f4e7b1-2d33-4a11-8f56-abcdef123456"),
                            RoleId = new Guid("5dcbdb75-d5c9-4109-ab52-fd869be79532")
                        },
                        new
                        {
                            UserId = new Guid("e5c2a9b3-4a67-4f89-8d23-556677889900"),
                            RoleId = new Guid("5dcbdb75-d5c9-4109-ab52-fd869be79532")
                        },
                        new
                        {
                            UserId = new Guid("a7d3c5e2-9b41-4f12-8f34-123456789abc"),
                            RoleId = new Guid("a3f06ed0-4bca-4e98-8bef-4cd91e64e2a1")
                        },
                        new
                        {
                            UserId = new Guid("ac31b0bb-d05a-438d-be06-9bfe3323cf08"),
                            RoleId = new Guid("a3f06ed0-4bca-4e98-8bef-4cd91e64e2a1")
                        },
                        new
                        {
                            UserId = new Guid("29965aaa-46cf-4829-93b8-e38401be7547"),
                            RoleId = new Guid("a3f06ed0-4bca-4e98-8bef-4cd91e64e2a1")
                        },
                        new
                        {
                            UserId = new Guid("fc95b3fa-f342-4172-ac8b-5b35951ad760"),
                            RoleId = new Guid("8c384109-e13f-4556-a810-ab9ba28161a2")
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<System.Guid>", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("LoginProvider")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("Name")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("GlowCare.Entities.Models.Employee", b =>
                {
                    b.HasOne("GlowCare.Entities.Models.GlowUser", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("GlowCare.Entities.Models.EmployeeService", b =>
                {
                    b.HasOne("GlowCare.Entities.Models.Employee", "Employee")
                        .WithMany("EmployeeServices")
                        .HasForeignKey("EmployeeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("GlowCare.Entities.Models.Service", "Service")
                        .WithMany("EmployeeServices")
                        .HasForeignKey("ServiceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Employee");

                    b.Navigation("Service");
                });

            modelBuilder.Entity("GlowCare.Entities.Models.GlowUser", b =>
                {
                    b.HasOne("GlowCare.Entities.Models.Membership", "Membership")
                        .WithMany("Users")
                        .HasForeignKey("MembershipId");

                    b.Navigation("Membership");
                });

            modelBuilder.Entity("GlowCare.Entities.Models.Procedure", b =>
                {
                    b.HasOne("GlowCare.Entities.Models.Employee", "Employee")
                        .WithMany("Procedures")
                        .HasForeignKey("EmployeeId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("GlowCare.Entities.Models.Service", "Service")
                        .WithMany("Procedures")
                        .HasForeignKey("ServiceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("GlowCare.Entities.Models.GlowUser", "User")
                        .WithMany("Procedures")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Employee");

                    b.Navigation("Service");

                    b.Navigation("User");
                });

            modelBuilder.Entity("GlowCare.Entities.Models.Review", b =>
                {
                    b.HasOne("GlowCare.Entities.Models.Employee", "Employee")
                        .WithMany("Reviews")
                        .HasForeignKey("EmployeeId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("GlowCare.Entities.Models.Procedure", "Procedure")
                        .WithMany("Reviews")
                        .HasForeignKey("ProcedureId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.HasOne("GlowCare.Entities.Models.Service", "Service")
                        .WithMany()
                        .HasForeignKey("ServiceId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("GlowCare.Entities.Models.GlowUser", "User")
                        .WithMany("Reviews")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Employee");

                    b.Navigation("Procedure");

                    b.Navigation("Service");

                    b.Navigation("User");
                });

            modelBuilder.Entity("GlowCare.Entities.Models.Schedule", b =>
                {
                    b.HasOne("GlowCare.Entities.Models.Employee", "Employee")
                        .WithMany("Schedules")
                        .HasForeignKey("EmployeeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Employee");
                });

            modelBuilder.Entity("GlowCare.Entities.Models.Service", b =>
                {
                    b.HasOne("GlowCare.Entities.Models.Category", "Category")
                        .WithMany("Services")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Category");
                });

            modelBuilder.Entity("GlowCare.Entities.Models.SpecialistApplication", b =>
                {
                    b.HasOne("GlowCare.Entities.Models.GlowUser", "User")
                        .WithMany("SpecialistApplications")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<System.Guid>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole<System.Guid>", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<System.Guid>", b =>
                {
                    b.HasOne("GlowCare.Entities.Models.GlowUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<System.Guid>", b =>
                {
                    b.HasOne("GlowCare.Entities.Models.GlowUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<System.Guid>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole<System.Guid>", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("GlowCare.Entities.Models.GlowUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<System.Guid>", b =>
                {
                    b.HasOne("GlowCare.Entities.Models.GlowUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("GlowCare.Entities.Models.Category", b =>
                {
                    b.Navigation("Services");
                });

            modelBuilder.Entity("GlowCare.Entities.Models.Employee", b =>
                {
                    b.Navigation("EmployeeServices");

                    b.Navigation("Procedures");

                    b.Navigation("Reviews");

                    b.Navigation("Schedules");
                });

            modelBuilder.Entity("GlowCare.Entities.Models.GlowUser", b =>
                {
                    b.Navigation("Procedures");

                    b.Navigation("Reviews");

                    b.Navigation("SpecialistApplications");
                });

            modelBuilder.Entity("GlowCare.Entities.Models.Membership", b =>
                {
                    b.Navigation("Users");
                });

            modelBuilder.Entity("GlowCare.Entities.Models.Procedure", b =>
                {
                    b.Navigation("Reviews");
                });

            modelBuilder.Entity("GlowCare.Entities.Models.Service", b =>
                {
                    b.Navigation("EmployeeServices");

                    b.Navigation("Procedures");
                });
#pragma warning restore 612, 618
        }
    }
}
